
sudo: required
services:
  - ftp
language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage
  - npm run build
after_success:
  - npm run coveralls
  - chmod +x ftp-upload
  - cd ./build
  - find . -type d -exec ../ftp-upload {} >/dev/null 2>&1 \;
  - echo '[+] Uploaded'