
sudo: required
language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
before_install:
  sudo apt-get install -y expect
script:
  - npm test -- --coverage
  - npm run build
after_success:
  - npm run coveralls
  - chmod +x ftp-upload
  - cd ./build
  - find . -type d -exec ../ftp-upload {} \;
  - echo '[+] Uploaded'