language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage
  - npm run build
after_script:
  - npm run coveralls
after_success:
  - echo "user is $SFTP_USER"
  - echo "$SFTP_PASSWORD"
  - cd build
  - find . -type f
  - find . -type f -exec curl --ftp-create-dirs -T {} sftp://${SFTP_USER}:${SFTP_PASSWORD}@ssh.strato.de +
  - echo '[+] Uploaded'