language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage
  - npm run build
after_success:
  - npm run coveralls
  - echo "user is $SFTP_USER"
  - echo "$SFTP_PASSWORD"
  - cd ./build
  - find . -type f
  - find . -type f -exec curl --ftp-create-dirs -T {} ftp://ssh.strato.de --user ${SFTP_USER}:${SFTP_PASSWORD} \;
  - echo '[+] Uploaded'