language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage
  - npm run build
after_script:
  - npm run coveralls
after_success:
  - echo '[+] Build successful. Starting Deployment...'
  - echo '[+] Uploading built files to server...'
  - find ./build -type f
  - find ./build -type f -exec curl --ftp-create-dirs -T {} sftp://${SFTP_USER}:${SFTP_PASSWORD}@ssh.strato.de +
  - echo '[+] Uploaded'