language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage
  - npm run build
after_script:
  - npm run coveralls
deploy:
  - find ./build -type f -exec curl --ftp-create-dirs -T {} sftp://${SFTP_USER}:${SFTP_PASSWORD}@ssh.strato.de +