#!/usr/bin/expect
set SERVER ssh.strato.de
set DIR [lindex $argv 0];
cd $DIR

spawn sftp $env(SFTP_USER)@$SERVER
expect {
    "*(yes/no)?" { 
        send "yes\n" 
        expect "*password:" send "$env(SFTP_PWD)\n"
    }
    "*password:" { send "$env(SFTP_PWD)\n" }
}
expect "sftp>"
send "mkdir $DIR\n"
expect "sftp>"
send "cd $DIR\n"
expect "sftp>"
send "mput *\n"
expect "sftp>"
send "close\n"
expect "sftp>"
send "bye\n"