#!/usr/bin/expect
set SERVER ssh.strato.de
set DIR [lindex $argv 0];
cd $DIR
set timeout 120

spawn sftp $env(SFTP_USER)@$SERVER
expect {
    "*(yes/no)?" { 
        send "yes\n"
        exp_continue
    } "*password:" { 
        send "$env(SFTP_PWD)\n"     
    }
}
expect "sftp>"
send "mkdir $DIR\n"
expect "sftp>"
send "cd $DIR\n"
expect "sftp>"
send "mput *\n"
expect "sftp>"
send "close\n"
expect "sftp>"
send "bye\n"
